### ISSUE TITLE
make problems

### ISSUE THREAD

**Issue by Jalagarto** [cocodataset/cocoapi#227]
I have installed cython and all other supposed necessary dependences, but when runing the make:
~...cocoapi-master/PyhonAPI$ make

... it's still not compiling it:

python setup.py build_ext --inplace
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    ext_modules= ext_modules
  File "/home/javier/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/javier/.local/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
    full_module_name=module_name)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 776, in compile
    return compile_single(source, options, full_module_name)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 725, in compile_single
    return run_pipeline(source, options, full_module_name)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 477, in run_pipeline
    context = options.create_context()
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 595, in create_context
    self.cplus, self.language_level, options=self)
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 78, in __init__
    from . import Builtin, CythonScope
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/home/javier/.local/lib/python2.7/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "Cython/Compiler/Scanning.pxd", line 18, in init Cython.Compiler.Parsing
ValueError: Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by jonperron** [comment]
I got the same problem @Jalagarto , and it seems that https://github.com/cocodataset/cocoapi/issues/221 solves this issue.

**Comment by Jamxscape** [comment]
Have you solved that??

**Comment by javi-clear-image-ai** [comment]
yes! I just installed it from conda, so I didn't have to make it...  https://anaconda.org/HCC/pycocotools

you can have a look here as well https://github.com/cocodataset/cocoapi/issues/221#issuecomment-428199249.

Regards!

**Comment by Jalagarto** [comment]
Yes. I just installed it from Conda on my linux machine, so I didn't have to make it:
https://anaconda.org/HCC/pycocotools  (not in windows yet)

You can also have a look at how they solved it here:
https://github.com/cocodataset/cocoapi/issues/221#issuecomment-428199249

**Comment by zhichaolei** [comment]
My python version is 3.6 (Anaconda), cython version is 0.29.21
During compiling, it keeps saying Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
Could anyone help me?

Thanks

**Comment by MassEast** [comment]
> My python version is 3.6 (Anaconda), cython version is 0.29.21
> During compiling, it keeps saying Cython.Compiler.Scanning.CompileTimeScope has the wrong size, try recompiling. Expected 32, got 40
> Could anyone help me?
> 
> Thanks

Same problem
