### ISSUE TITLE
评估时报错:'Results do not correspond to current coco set'

### ISSUE THREAD

**Issue by Erikfather** [cocodataset/cocoapi#230]

**Comment by muye5** [comment]
same problem encountered, only test-dev2018 supported? I upload the test-dev2014 detection results and show the same error info, still unsolved now.

**Comment by yuEzar** [comment]
I think the 316 line code has something wrong.

**Comment by bhyzhao** [comment]
Same problem to me when uploading result on test-dev2017. How to solve?
Traceback (most recent call last):
  File "/tmp/codalab/tmpOr43ec/run/program/run.py", line 70, in 
    cocoDt=cocoGt.loadRes(resFile)
  File "/tmp/codalab/tmpOr43ec/run/program/pycocokp/coco.py", line 304, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by ashkan-abbasi66** [comment]
The method `loadRes` in `coco.py` checks that whether the file containing detection results and the file containing ground truths are consistent or not. For each image in the ground truth file, there should be an annotation. 

It is checked with the following line of code from `loadRes` method:
```
assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
               'Results do not correspond to current coco set'
```

To resolve this problem, just use the correct file names for ground truths and results. You can use these: `instances_val2014.json` and `instances_val2014_fakebbox100_results.json`

**Comment by moin59** [comment]
For  **instances_val2014.json and instances_val2014_fakebbox100_results.json** are working fine in pycocoEvalDemo. But while try a new result with the same format its shows the error. Do you have any suggestion @ashkan-abbasi66. how do I evaluate my results instead of  **instances_val2014_fakebbox100_results.json**

**Comment by ashkan-abbasi66** [comment]
Dear @moin59 
Store your ground truth annotations and results in seperate JSON files. The files must be appropriately formatted.
For annotations file, see http://cocodataset.org/#format-data
For results file, see http://cocodataset.org/#format-results

Here is a simple and light-wight example. Let's assume that we want to create annotations and results files for an object detection task (So, we are interested in bounding boxes).

Annotation file: `ann.json`
```json
{"images":[{"id": 73}],"annotations":[{"image_id":73,"category_id":1,"bbox":[10,10,50,100],"id":1,"iscrowd": 0,"area": 10}],"categories": [{"id": 1, "name": "person"}, {"id": 2, "name": "bicycle"}, {"id": 3, "name": "car"}]}
``` 

Result file: `res.json`
```json
[{"image_id":73,"category_id":1,"bbox":[10,10,50,100],"score":0.9}]
```

**Comment by niazahamd89** [comment]
Hi folks let me clear on my problem I train the model on both train and evl coco dataset as a result my model generates output in .ckpt format which i prior use for estimation of pose but i am confuse how i can get the .json file for evaluation of model to know the AP or AR. is the model generates this file by self?

**Comment by ZP-Guo** [comment]
> Dear @moin59
> Store your ground truth annotations and results in seperate JSON files. The files must be appropriately formatted.
> For annotations file, see http://cocodataset.org/#format-data
> For results file, see http://cocodataset.org/#format-results
> 
> Here is a simple and light-wight example. Let's assume that we want to create annotations and results files for an object detection task (So, we are interested in bounding boxes).
> 
> Annotation file: `ann.json`
> 
> ```json
> {"images":[{"id": 73}],"annotations":[{"image_id":73,"category_id":1,"bbox":[10,10,50,100],"id":1,"iscrowd": 0,"area": 10}],"categories": [{"id": 1, "name": "person"}, {"id": 2, "name": "bicycle"}, {"id": 3, "name": "car"}]}
> ```
> 
> Result file: `res.json`
> 
> ```json
> [{"image_id":73,"category_id":1,"bbox":[10,10,50,100],"score":0.9}]
> ```

Hi, @ashkan-abbasi66, 
I want to use cocoapi to evaluate my results, but I do not how to get "score" that comes from 
`[{"image_id":73,"category_id":1,"bbox":[10,10,50,100],"score":0.9}]`. 
 And my net does not output the confidence or probability. Could you tell me how to get it.

**Comment by kuangxiaoye** [comment]
可能是因为你用的coco - 2017

而cocoapi是2014
