### ISSUE TITLE
pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by LinZuo** [cocodataset/cocoapi#259]
I am trying to run the model_main.py under tensorflow object detection API, which needs the successful installation of CocoAPI. I have followed the instruction to install CocoAPI, including doing make and moving the pycocotools to research folder, but it doesn't seem to work and I kept getting the error that I attached below:

Traceback (most recent call last):
  File "object_detection/model_main.py", line 26, in <module>
    from object_detection import model_lib
  File "/hdd/bassconnections/Lin/models/research/object_detection/model_lib.py", line 27, in <module>
    from object_detection import eval_util
  File "/hdd/bassconnections/Lin/models/research/object_detection/eval_util.py", line 27, in <module>
    from object_detection.metrics import coco_evaluation
  File "/hdd/bassconnections/Lin/models/research/object_detection/metrics/coco_evaluation.py", line 20, in <module>
    from object_detection.metrics import coco_tools
  File "/hdd/bassconnections/Lin/models/research/object_detection/metrics/coco_tools.py", line 47, in <module>
    from pycocotools import coco
  File "/hdd/bassconnections/Lin/models/research/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/hdd/bassconnections/Lin/models/research/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: /hdd/bassconnections/Lin/models/research/pycocotools/_mask.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object

Anyone has any idea?

**Comment by Caduunb** [comment]
It seems that you created the `models/research` directories in a path other than inside the `tensorflow` path. Maybe this will solve your problem.

**Comment by ridasalam** [comment]
@Caduunb , hey can you please explain what you meant? I'm having the same issue

**Comment by Caduunb** [comment]
If I remember right, you'll have to clone the tensorflow repository in order to install it. There will be a folder named "research" inside it. This is the one the COCO installation procedures refer to. Things must be under the original tensorflow root. Hopefully this is will help you :)
