### ISSUE TITLE
How to download specific classes from COCO dataset

### ISSUE THREAD

**Issue by bluetooth12** [cocodataset/cocoapi#271]
I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?

**Comment by bluetooth12** [comment]
I downloaded the images with the code below. Now I think that I need the annotations (bounding boxes and labels). 
from pycocotools.coco import COCO
import requests

coco = COCO('cocoapi/annotations/instances_train2017.json')
cats = coco.loadCats(coco.getCatIds())
nms=[cat['name'] for cat in cats]
print('COCO categories: \n{}\n'.format(' '.join(nms)))

catIds = coco.getCatIds(catNms=['person'])
imgIds = coco.getImgIds(catIds=catIds )
images = coco.loadImgs(imgIds)
print("imgIds: ", imgIds)
print("images: ", images)

for im in images:
    print("im: ", im)
    img_data = requests.get(im['coco_url']).content
    with open('downloaded_images/' + im['file_name'], 'wb') as handler:
        handler.write(img_data)

**Comment by bluetooth12** [comment]
Annotations seem to be downloaded this way:
#Download annotations
with open('annotations_download_' + classes + '.csv', mode='w', newline='') as annot:
    for im in images:
        annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
        anns = coco.loadAnns(annIds)
        for i in range(len(anns)):  
            annot_writer = csv.writer(annot)
            #annot_writer.writerow([im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], classes])
            annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), classes])
            #print("anns: ", im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], 'person')
annot.close()

**Comment by thekhieu** [comment]
can you share your python code?
thank you.

**Comment by bluetooth12** [comment]
I have shared my python code. See the two previous posts.

**Comment by jwangjie** [comment]
> Annotations seem to be downloaded this way:
> #Download annotations
> with open('annotations_download_' + classes + '.csv', mode='w', newline='') as annot:
> for im in images:
> annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> anns = coco.loadAnns(annIds)
> for i in range(len(anns)):
> annot_writer = csv.writer(annot)
> #annot_writer.writerow([im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], classes])
> annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), classes])
> #print("anns: ", im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], 'person')
> annot.close()

Thank you @bluetooth12 for sharing your codes. I wonder what "classes" is? Is it "catIds"? Thank you.

**Comment by thekhieu** [comment]
@jwangjie 
catIds = coco.getCatIds(catNms=['person'])
class is person

**Comment by Aakash95-co** [comment]
> I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?

from pycocotools.coco import COCO
import requests

coco = COCO('cocoapi/annotations/instances_train2017.json')
cats = coco.loadCats(coco.getCatIds())
nms=[cat['name'] for cat in cats]

catIds = coco.getCatIds(catNms=['car'])
imgIds = coco.getImgIds(catIds=catIds )
images = coco.loadImgs(imgIds)

# make folder test_xx_downloaded_images
for im in images:
	#print("im: ", im)
	img_data = requests.get(im['coco_url']).content
	with open('test_xx_downloaded_images/' + im['file_name'], 'wb') as handler:
	handler.write(img_data)


import csv

with open('test_xx_annotations_download_' + 'car_bus' + '.csv', mode='w', newline='') as annot:
	for im in images:
		annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
		anns = coco.loadAnns(annIds)
		for i in range(len(anns)):
			annot_writer = csv.writer(annot)
			annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), 'car'])

**Comment by saqibshakeel035** [comment]
> > I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?
> 
> from pycocotools.coco import COCO
> import requests
> 
> coco = COCO('cocoapi/annotations/instances_train2017.json')
> cats = coco.loadCats(coco.getCatIds())
> nms=[cat['name'] for cat in cats]
> 
> catIds = coco.getCatIds(catNms=['car'])
> imgIds = coco.getImgIds(catIds=catIds )
> images = coco.loadImgs(imgIds)
> 
> # make folder test_xx_downloaded_images
> for im in images:
> #print("im: ", im)
> img_data = requests.get(im['coco_url']).content
> with open('test_xx_downloaded_images/' + im['file_name'], 'wb') as handler:
> handler.write(img_data)
> 
> import csv
> 
> with open('test_xx_annotations_download_' + 'car_bus' + '.csv', mode='w', newline='') as annot:
> for im in images:
> annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> anns = coco.loadAnns(annIds)
> for i in range(len(anns)):
> annot_writer = csv.writer(annot)
> annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), 'car'])

This code works fine to download the images but when I see the images, instead of downloading the images of class specified, it downloads random images.
I am not sure if that is a glitch or something??

**Comment by RxIam** [comment]
d

**Comment by SravaniTeeparthi** [comment]
Here is my code that creates a csv file with keyboard bounding boxes. I will later use this csv file to create tfrecord.

```python
from pycocotools.coco import COCO
import sys
import pandas as pd


# Initializations (make them as arguments)
cat_of_interest = "keyboard" # supports only one category.
ann_file = "/media/VjSravani/Sravani/public-datasets/coco/annotations/instances_train2017.json"
csv_save_path = "/media/VjSravani/Sravani/public-datasets/coco/annotations/keyboard-trn-bboxes.csv"

# COCO instance
coco = COCO(ann_file)

# get category id
cat_id  = coco.getCatIds(catNms=[cat_of_interest])

# get annotation ids for current category
ann_ids = coco.getAnnIds(catIds=cat_id, iscrowd=None)
all_ann = coco.loadAnns(ann_ids)
 
# Loop through each annotation and create a data frame with necessary
#     information to create csv file. This file later aids in creating
#     tensorflow record.

df_rows = []
for i in range(0, len(all_ann)):
    cur_ann    = all_ann[i]
    cbbox      = cur_ann["bbox"]
    cimg_info  = coco.loadImgs(cur_ann["image_id"])

    if(len(cimg_info) > 1):
        print("ERROR: More than one image got loaded")
        sys.exit(1)
        
    filename   = cimg_info[0]["file_name"]
    cur_class  = cat_of_interest
    width    = cimg_info[0]["width"]
    height   = cimg_info[0]["height"]
    xmin     = int(cbbox[0])
    ymin     = int(cbbox[1])
    xmax     = min(int(xmin + cbbox[2]), width-1)
    ymax     = min(int(ymin + cbbox[3]), height-1)

    df_rows  = df_rows + [[filename, str(width), str(height), cur_class,
                           str(xmin), str(ymin), str(xmax), str(ymax)]]

df=pd.DataFrame(df_rows, columns=["filename", "width", "height", "class",
                           "xmin", "ymin", "xmax", "ymax"])
df.to_csv(csv_save_path)
```

**Comment by Adblu** [comment]
How do you convert csv back to json coco format ?

**Comment by amalmathews** [comment]
how to convert csv back to json or how to filter instances_train2017.json annotations only for a specific class

**Comment by amalmathews** [comment]
> Annotations seem to be downloaded this way:
> #Download annotations
> with open('annotations_download_' + classes + '.csv', mode='w', newline='') as annot:
> for im in images:
> annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> anns = coco.loadAnns(annIds)
> for i in range(len(anns)):
> annot_writer = csv.writer(annot)
> #annot_writer.writerow([im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], classes])
> annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), classes])
> #print("anns: ", im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], 'person')
> annot.close()

how to convert csv back to json or how to filter instances_train2017.json annotations only for a specific class

**Comment by Rrojin11** [comment]
> Annotations seem to be downloaded this way:
> #Download annotations
> with open('annotations_download_' + classes + '.csv', mode='w', newline='') as annot:
> for im in images:
> annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> anns = coco.loadAnns(annIds)
> for i in range(len(anns)):
> annot_writer = csv.writer(annot)
> #annot_writer.writerow([im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], classes])
> annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), classes])
> #print("anns: ", im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], 'person')
> annot.close()

how long does it take to download one class dataset??

**Comment by elementdl** [comment]
> > I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?
> 
> from pycocotools.coco import COCO
> import requests
> 
> coco = COCO('cocoapi/annotations/instances_train2017.json')
> cats = coco.loadCats(coco.getCatIds())
> nms=[cat['name'] for cat in cats]
> 
> catIds = coco.getCatIds(catNms=['car'])
> imgIds = coco.getImgIds(catIds=catIds )
> images = coco.loadImgs(imgIds)
> 
> # make folder test_xx_downloaded_images
> for im in images:
> #print("im: ", im)
> img_data = requests.get(im['coco_url']).content
> with open('test_xx_downloaded_images/' + im['file_name'], 'wb') as handler:
> handler.write(img_data)
> 
> import csv
> 
> with open('test_xx_annotations_download_' + 'car_bus' + '.csv', mode='w', newline='') as annot:
> for im in images:
> annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> anns = coco.loadAnns(annIds)
> for i in range(len(anns)):
> annot_writer = csv.writer(annot)
> annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), 'car'])

Hi,

I tried to use this code but it didn't work.
I'm on windows, and i only used the code that before "import csv"

I get this :

C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/oberton/Desktop/Stage/projet/bases_de_donnees/COCO/test.py
loading annotations into memory...
Traceback (most recent call last):
  File "C:/Users/oberton/Desktop/Stage/projet/bases_de_donnees/COCO/test.py", line 4, in <module>
    coco = COCO('annotations_trainval2017/annotations/instances_train2017.json')
  File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pycocotools\coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
  File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
MemoryError

Process finished with exit code 1


Does anyone know why it doesn't work for me?

**Comment by opditextest** [comment]
> > Annotations seem to be downloaded this way:
> > #Download annotations
> > with open('annotations_download_' + classes + '.csv', mode='w', newline='') as annot:
> > for im in images:
> > annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> > anns = coco.loadAnns(annIds)
> > for i in range(len(anns)):
> > annot_writer = csv.writer(annot)
> > #annot_writer.writerow([im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], classes])
> > annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), classes])
> > #print("anns: ", im['coco_url'], anns[i]['bbox'][0], anns[i]['bbox'][1], anns[i]['bbox'][0] + anns[i]['bbox'][2], anns[i]['bbox'][1] + anns[i]['bbox'][3], 'person')
> > annot.close()
> 
> how long does it take to download one class dataset??

It depends on how big the dataset of a particular class is. So, it may take 5 minutes for the class like traffic sign (STOP) but can take up to hours for the class CAR.

**Comment by tailtq** [comment]
> > > I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?
> > 
> > 
> > from pycocotools.coco import COCO
> > import requests
> > coco = COCO('cocoapi/annotations/instances_train2017.json')
> > cats = coco.loadCats(coco.getCatIds())
> > nms=[cat['name'] for cat in cats]
> > catIds = coco.getCatIds(catNms=['car'])
> > imgIds = coco.getImgIds(catIds=catIds )
> > images = coco.loadImgs(imgIds)
> > # make folder test_xx_downloaded_images
> > for im in images:
> > #print("im: ", im)
> > img_data = requests.get(im['coco_url']).content
> > with open('test_xx_downloaded_images/' + im['file_name'], 'wb') as handler:
> > handler.write(img_data)
> > import csv
> > with open('test_xx_annotations_download_' + 'car_bus' + '.csv', mode='w', newline='') as annot:
> > for im in images:
> > annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> > anns = coco.loadAnns(annIds)
> > for i in range(len(anns)):
> > annot_writer = csv.writer(annot)
> > annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), 'car'])
> 
> This code works fine to download the images but when I see the images, instead of downloading the images of class specified, it downloads random images.
> I am not sure if that is a glitch or something??

It's late to response but actually they are all correct. I've skimmed through some of the images in the official website and some of the labels are very small.

**Comment by HansiIMW** [comment]
I've tried downloading only the images for the tag 'person', but it quits after ~6000 downloaded images, citing the following error: Anybody know whats going on here? 
`
  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\Users\Owner\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)

  File "<string>", line 3, in raise_from

  File "C:\Users\Owner\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 1344, in getresponse
    response.begin()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()

  File "C:\Users\Owner\anaconda3\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")

  File "C:\Users\Owner\anaconda3\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)

ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\Owner\ownCloud_MMI\13_Studentische Mitarbeiter\Hans\001_DyPro\003_Coding\COCO\download.py", line 24, in <module>
    img_data = requests.get(im['coco_url']).content

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)

  File "C:\Users\Owner\anaconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

**Comment by tailtq** [comment]
@HansiIMW Can you send your code here? I think [this answer](https://stackoverflow.com/a/8814832/7985083) is reasonable.

**Comment by Hipsterian77H** [comment]
The last for is inside the for im in images? 

Thanks

**Comment by trungtv94** [comment]
@bluetooth12 Thanks you for your sharing. I have a question that as I check, each image have only 1 box for each class. Example: "000000000315.jpg,45,169,572,290,person" , but when I open image, it has many person. is it right? pls check it and explain for me. Thanks you very much.

**Comment by Jalagarto** [comment]
Find here my module to download the images of one class/category (copied from the above code) and to filter the json for this category

https://github.com/Jalagarto/coco_utils/blob/main/coco_categ_selection.py

It has been tested with one class, but it should be straight forward to adapt it for multiclass selection.
This would be the main method for the json, but I also reorganize the images and annotations IDs:

```
    def filter_json_by_category(self, new_json_path):
        """creates a new json with the desired category"""
        # {'supercategory': 'person', 'id': 1, 'name': 'person'}
        ### Filter images:
        print("Filtering the annotations ... ")
        json_parent = os.path.split(new_json_path)[0]
        os.makedirs(json_parent, exist_ok=True)
        imgs_ids = [x['id'] for x in self.images] # get img_ids of imgs with the category
        new_imgs = [x for x in self.coco.dataset['images'] if x['id'] in imgs_ids]
        catIds = self.catIds
        ### Filter annotations
        new_annots = [x for x in self.coco.dataset['annotations'] if x['category_id'] in catIds]
        ### Reorganize the ids
        new_imgs, annotations = self.modify_ids(new_imgs, new_annots)
        ### Filter categories
        new_categories = [x for x in self.coco.dataset['categories'] if x['id'] in catIds]
        print("new_categories: ", new_categories)
        data = {
            "info": self.coco.dataset['info'],
            "licenses": self.coco.dataset['licenses'],
            "images": new_imgs, 
            "annotations": new_annots,
            "categories": new_categories 
            }
        print("saving json: ")
        with open(new_json_path, 'w') as f:
            json.dump(data, f)
```

**Comment by sowmyakavali** [comment]
> > > I would like the images and annotations for cars and people only in the COCO dataset. I would also like to have them in a csv format. Can anybody point me in a good direction?
> > 
> > 
> > from pycocotools.coco import COCO
> > import requests
> > coco = COCO('cocoapi/annotations/instances_train2017.json')
> > cats = coco.loadCats(coco.getCatIds())
> > nms=[cat['name'] for cat in cats]
> > catIds = coco.getCatIds(catNms=['car'])
> > imgIds = coco.getImgIds(catIds=catIds )
> > images = coco.loadImgs(imgIds)
> > # make folder test_xx_downloaded_images
> > for im in images:
> > #print("im: ", im)
> > img_data = requests.get(im['coco_url']).content
> > with open('test_xx_downloaded_images/' + im['file_name'], 'wb') as handler:
> > handler.write(img_data)
> > import csv
> > with open('test_xx_annotations_download_' + 'car_bus' + '.csv', mode='w', newline='') as annot:
> > for im in images:
> > annIds = coco.getAnnIds(imgIds=im['id'], catIds=catIds, iscrowd=None)
> > anns = coco.loadAnns(annIds)
> > for i in range(len(anns)):
> > annot_writer = csv.writer(annot)
> > annot_writer.writerow(['downloaded_images/' + im['file_name'], int(round(anns[i]['bbox'][0])), int(round(anns[i]['bbox'][1])), int(round(anns[i]['bbox'][0] + anns[i]['bbox'][2])), int(round(anns[i]['bbox'][1] + anns[i]['bbox'][3])), 'car'])
> 
> Hi,
> 
> I tried to use this code but it didn't work.
> I'm on windows, and i only used the code that before "import csv"
> 
> I get this :
> 
> C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/oberton/Desktop/Stage/projet/bases_de_donnees/COCO/test.py
> loading annotations into memory...
> Traceback (most recent call last):
> File "C:/Users/oberton/Desktop/Stage/projet/bases_de_donnees/COCO/test.py", line 4, in
> coco = COCO('annotations_trainval2017/annotations/instances_train2017.json')
> File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pycocotools\coco.py", line 84, in **init**
> dataset = json.load(open(annotation_file, 'r'))
> File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json__init__.py", line 293, in load
> return loads(fp.read(),
> File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json__init__.py", line 357, in loads
> return _default_decoder.decode(s)
> File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "C:\Users\oberton\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
> obj, end = self.scan_once(s, idx)
> MemoryError
> 
> Process finished with exit code 1
> 
> Does anyone know why it doesn't work for me?


It seems like you don't have sufficient disk space in your system.

**Comment by andirahmadiansah** [comment]
> I have shared my python code. See the two previous posts.

What about small object, can you shared python code? I confuse to get small object from coco dataset.

Thank's alot
