### ISSUE TITLE
 ERROR: Failed cleaning build dir for pycocotools

### ISSUE THREAD

**Issue by sainimohit23** [cocodataset/cocoapi#328]
```


(tensorflow) E:\New_folder\Mask_RCNN>pip3 install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
Collecting pycocotools from git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\babban\appdata\local\temp\pip-install-wc3k8g93\pycocotools
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\Babban\AppData\Local\Temp\pip-install-wc3k8g93\pycocotools'
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\babban\appdata\local\conda\conda\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Babban\AppData\Local\Temp\pip-wheel-7r9t5ol7' --python-tag cp35
       cwd: C:\Users\Babban\AppData\Local\Temp\pip-install-wc3k8g93\pycocotools\PythonAPI
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-3.5\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-3.5\pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\babban\appdata\local\conda\conda\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Babban\AppData\Local\Temp\pip-install-wc3k8g93\pycocotools
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Babban\AppData\Local\Temp\pip-install-wc3k8g93\pycocotools\PythonAPI\setup.py", line 25, in <module>
      cythonize(ext_modules)
    File "c:\users\babban\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 966, in cythonize
      aliases=aliases)
    File "c:\users\babban\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 810, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "c:\users\babban\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\Cython\Build\Dependencies.py", line 109, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pycocotools/_mask.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\babban\appdata\local\conda\conda\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Babban\AppData\Local\Temp\pip-record-phc6du7q\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Babban\AppData\Local\Temp\pip-install-wc3k8g93\pycocotools\PythonAPI
    Complete output (6 lines):
    running install
    running build
    running build_py
    running build_ext
    building 'pycocotools._mask' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\babban\appdata\local\conda\conda\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"'; __file__='"'"'C:\\Users\\Babban\\AppData\\Local\\Temp\\pip-install-wc3k8g93\\pycocotools\\PythonAPI\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Babban\AppData\Local\Temp\pip-record-phc6du7q\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

```

**Comment by MissionBio** [comment]
I have the same issue, did you solve this?

**Comment by sainimohit23** [comment]
@MissionBio, unfortunately, I couldn't. You can do two things.

1) Clone it to google colab and process your code there.
2) Instead of installing the requirements. I cloned it to my computer and called the modules from my main file and it worked.

**Comment by khaledxdelahkk** [comment]
hello
click here https://www.microsoft.com/en-us/download/details.aspx?id=48145 
and try to install both "vc_redist.x64.exe" and  "vc_redist.x86.exe"

**Comment by virafpatrawala** [comment]
If you are working in Conda, you can follow the below steps to be able to install, import and use this library quite smoothly.

```
### Enter the below in your Conda Command Prompt ###
# Create a new environment
conda create -n <envName>
# Activate the environment
conda activate <envName>
# Install cython
pip install cython
# Install git
conda install -c anaconda git
# Install pycocotools from this GitHub rep
pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
```

Additionally, I have recently written an entire post on [exploring and manipulating the COCO dataset](https://towardsdatascience.com/master-the-coco-dataset-for-semantic-image-segmentation-part-1-of-2-732712631047). Do have a look.

**Comment by Robotatron** [comment]
> If you are working in Conda, you can follow the below steps to be able to install, import and use this library quite smoothly.
> 
> ```
> ### Enter the below in your Conda Command Prompt ###
> # Create a new environment
> conda create -n <envName>
> # Activate the environment
> conda activate <envName>
> # Install cython
> pip install cython
> # Install git
> conda install -c anaconda git
> # Install pycocotools from this GitHub rep
> pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
> ```
> 
> Additionally, I have recently written an entire post on [exploring and manipulating the COCO dataset](https://towardsdatascience.com/master-the-coco-dataset-for-semantic-image-segmentation-part-1-of-2-732712631047). Do have a look.

Does not work -> `Error Failed cleaning build dir for pycocotools`

```
Collecting git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\sergiy.shebotnov\appdata\local\temp\pip-req-build-fonl7lco
  Running command git clone --filter=blob:none --quiet https://github.com/philferriere/cocoapi.git 'C:\Users\Sergiy.Shebotnov\AppData\Local\Temp\pip-req-build-fonl7lco'
  Resolved https://github.com/philferriere/cocoapi.git to commit 2929bd2ef6b451054755dfd7ceb09278f935f7ad
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-3.8\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-3.8\pycocotools
      running build_ext
      building 'pycocotools._mask' extension
      creating build\temp.win-amd64-3.8
      creating build\temp.win-amd64-3.8\common
      creating build\temp.win-amd64-3.8\Release
      creating build\temp.win-amd64-3.8\Release\pycocotools
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.shebotnov\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
  Running setup.py clean for pycocotools
  error: subprocess-exited-with-error

  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Sergiy.Shebotnov\AppData\Local\Temp\pip-req-build-fonl7lco\PythonAPI\setup.py", line 25, in <module>
          cythonize(ext_modules)
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'pycocotools/_mask.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for pycocotools
Failed to build pycocotools
Installing collected packages: pycocotools
  Running setup.py install for pycocotools ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pycocotools did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      running install
      C:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'pycocotools._mask' extension
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tc../common/maskApi.c /Fobuild\temp.win-amd64-3.8\Release\../common/maskApi.obj
      maskApi.c
      "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\lib\site-packages\numpy\core\include -I../common -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\include -IC:\Users\Sergiy.Shebotnov\Miniconda3\envs\mmdet\Include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" /Tcpycocotools/_mask.c /Fobuild\temp.win-amd64-3.8\Release\pycocotools/_mask.obj
      _mask.c
      c:\users\sergiy.shebotnov\miniconda3\envs\mmdet\include\pyconfig.h(205): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pycocotools

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```
