### ISSUE TITLE
i did ''pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI''

### ISSUE THREAD

**Issue by Brandy24** [cocodataset/cocoapi#345]
ERROR: Command errored out with exit status 1:
     command: 'C:\Users\jennyLu\Anaconda3\envs\tensorflow1\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jennyLu\\AppData\\Local\\Temp\\pip-install-09fojtbx\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\jennyLu\\AppData\\Local\\Temp\\pip-install-09fojtbx\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\jennyLu\AppData\Local\Temp\pip-install-09fojtbx\pycocotools\pip-egg-info'
         cwd: C:\Users\jennyLu\AppData\Local\Temp\pip-install-09fojtbx\pycocotools\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jennyLu\Anaconda3\envs\tensorflow1\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jennyLu\\AppData\\Local\\Temp\\pip-install-09fojtbx\\pycocotools\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by virafpatrawala** [comment]
If you are working in Conda, you can follow the below steps to be able to install, import and use this library quite smoothly.

```
### Enter the below in your Conda Command Prompt ###
# Create a new environment
conda create -n <envName>
# Activate the environment
conda activate <envName>
# Install cython
pip install cython
# Install git
conda install -c anaconda git
# Install pycocotools from this GitHub rep
pip install git+https://github.com/philferriere/cocoapi.git#egg=pycocotools^&subdirectory=PythonAPI
```

Additionally, I have recently written an entire post on [exploring and manipulating the COCO dataset](https://towardsdatascience.com/master-the-coco-dataset-for-semantic-image-segmentation-part-1-of-2-732712631047). Do have a look.

**Comment by gadgetman4u** [comment]
The last line for installing pycocotools doesn't work, I get this error:

Collecting pycocotools
  Cloning https://github.com/philferriere/cocoapi.git to /tmp/pip-install-e6rlcqi6/pycocotools_624b720aa7bf48449a99fcf7dc03d4ed
ERROR: Command errored out with exit status 128: git clone -q https://github.com/philferriere/cocoapi.git /tmp/pip-install-e6rlcqi6/pycocotools_624b720aa7bf48449a99fcf7dc03d4ed Check the logs for full command output.

**Comment by Shrivardhana** [comment]
can we install the zip file  or the following link....??
https://github.com/cocodataset/cocoapi.git

**Comment by kakitGH** [comment]
> The last line for installing pycocotools doesn't work, I get this error:
> 
> Collecting pycocotools
> Cloning https://github.com/philferriere/cocoapi.git to /tmp/pip-install-e6rlcqi6/pycocotools_624b720aa7bf48449a99fcf7dc03d4ed
> ERROR: Command errored out with exit status 128: git clone -q https://github.com/philferriere/cocoapi.git /tmp/pip-install-e6rlcqi6/pycocotools_624b720aa7bf48449a99fcf7dc03d4ed Check the logs for full command output.

I have got the same error...
Collecting pycocotools
  Cloning https://github.com/philferriere/cocoapi.git to c:\users\hust\appdata\local\temp\pip-install-2s_41pis\pycocotools_ce9f801e4d85421abd96db62311528b8
  Running command git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\HUST\AppData\Local\Temp\pip-install-2s_41pis\pycocotools_ce9f801e4d85421abd96db62311528b8'
  fatal: unable to access 'https://github.com/philferriere/cocoapi.git/': Failed to connect to github.com port 443: Timed out
WARNING: Discarding git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI. Command errored out with exit status 128: git clone -q https://github.com/philferriere/cocoapi.git 'C:\Users\HUST\AppData\Local\Temp\pip-install-2s_41pis\pycocotools_ce9f801e4d85421abd96db62311528b8' Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pycocotools (unavailable)
ERROR: No matching distribution found for pycocotools (unavailable)

**Comment by ritikasarkar18** [comment]
```
pip3 install "git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
```
Worked for me (referring to https://github.com/cocodataset/cocoapi/issues/169#issuecomment-462528628 )
